// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/about";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/about")>;
      $$route?: undefined;
    },
    {
      path: "/users";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/users")>;
      $$route?: undefined;
    },
    {
      path: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
    },
    {
      path: "/users/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/users/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/users/[id]")>;
    },
    {
      path: "/games/story";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/games/story")>;
      $$route?: undefined;
    },
    {
      path: "/games/regular";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/games/regular")>;
      $$route?: undefined;
    },
    {
      path: "/games/gradient7";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/games/gradient7")>;
      $$route?: undefined;
    },
    {
      path: "/games/gradient4";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/games/gradient4")>;
      $$route?: undefined;
    },
    {
      path: "/games/countdown";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/games/countdown")>;
      $$route?: undefined;
    },
    {
      path: "/games/classical6";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/games/classical6")>;
      $$route?: undefined;
    },
    {
      path: "/games/classical";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/games/classical")>;
      $$route?: undefined;
    },
    {
      path: "/games/arcade";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/games/arcade")>;
      $$route?: undefined;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
    },
    {
      path: "/games";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/games")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/*404";
      id: "/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("./src/routes/[...404]")>;
      children?: undefined;
    },
    {
      path: "/about";
      id: "/about";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/about")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/users";
      id: "/users";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/users")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/:id";
          id: "/:id";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/users/[id]")>;
          $$route: FileRouteEagerRef<typeof import("./src/routes/users/[id]")>;
          children?: undefined;
        }
      ];
    },
    {
      path: "/games";
      id: "/games";
      page: true;
      $component: FileRouteLazyRef<typeof import("./src/routes/games")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/story";
          id: "/story";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/games/story")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/arcade";
          id: "/arcade";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/games/arcade")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/regular";
          id: "/regular";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/games/regular")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/gradient7";
          id: "/gradient7";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/games/gradient7")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/gradient4";
          id: "/gradient4";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/games/gradient4")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/countdown";
          id: "/countdown";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/games/countdown")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/classical";
          id: "/classical";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/games/classical")>;
          $$route?: undefined;
          children?: undefined;
        },
        {
          path: "/classical6";
          id: "/classical6";
          page: true;
          $component: FileRouteLazyRef<typeof import("./src/routes/games/classical6")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    }
  ];
}
